/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sota' at '17/07/24 23:05' with Gradle 2.14.1
 *
 * @author sota, @date 17/07/24 23:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
